#site
name: "Unclassed Blog"
url: https://unclassed.ca
baseurl: "/jekyllsite"
permalink: /:year/:month/:day/:title/ 


#Cover Page
coverheader: "Hey I'm Tyler"
coversub: "This is my blog where I will post about technology, life, farming, and more!"

collections:
  authors:
